import os
import re

# Refined replacements for better matching
replacements = {
    "de": [
        (r"MayankOS ist ein stolzer Nachfahre", "Dieses Projekt ist ein stolzer Nachfahre"),
        (r"MayankOS hat sich zu einer", "es hat sich zu einer"),
        (r"Was macht MayankOS anders\?", "Was macht es anders?"),
        (r"MayankOS enthält tiefgreifende", "dieses System enthält tiefgreifende"),
        (r"MayankOS nimmt dieses unglaubliche", "Diese Umgebung nimmt dieses unglaubliche"),
        (r"MayankOS bietet zwei primäre Wege", "Es werden zwei primäre Wege angeboten"),
        (r"MayankOS wurde speziell als", "Dieses System wurde speziell als"),
        (r"um MayankOS zur ultimativen", "um dies zur ultimativen"),
        (r"verwendet MayankOS jetzt Microsoft Edge", "verwendet das System jetzt Microsoft Edge"),
        (r"MayankOS macht den Wechsel einfach", "die Konfiguration macht den Wechsel einfach"),
        (r"MayankOS ist so konzipiert", "Diese Umgebung ist so konzipiert"),
        (r"Idee hinter MayankOS", "Idee hinter diesem Projekt"),
        (r"nutzen MayankOS", "nutzen diese Konfiguration"),
        (r"MayankOS unterstützt mehrere Umgebungen", "Es werden mehrere Umgebungen unterstützt"),
    ],
    "fr": [
        (r"MayankOS est un fier descendant", "Ce projet est un fier descendant"),
        (r"MayankOS a évolué", "il a évolué"),
        (r"Qu'est-ce qui rend MayankOS différent \?", "Qu'est-ce qui le rend différent ?"),
        (r"MayankOS inclut des optimisations", "ce système inclut des optimisations"),
        (r"MayankOS prend cette base", "Cet environnement prend cette base"),
        (r"MayankOS propose deux méthodes", "Deux méthodes principales sont proposées"),
        (r"MayankOS est spécifiquement conçu", "Ce système est spécifiquement conçu"),
        (r"pour faire de MayankOS la plateforme", "pour faire de celle-ci la plateforme"),
        (r"MayankOS utilise désormais Microsoft Edge", "le système utilise désormais Microsoft Edge"),
        (r"MayankOS facilite le changement", "la configuration facilite le changement"),
        (r"MayankOS est conçu pour être votre station", "Cet environnement est conçu pour être votre station"),
        (r"idée de MayankOS", "idée de ce projet"),
        (r"utilisent MayankOS", "utilisent cette configuration"),
        (r"MayankOS prend en charge plusieurs environnements", "Plusieurs environnements sont pris en charge"),
    ],
    "ru": [
        (r"MayankOS является гордым потомком", "Этот проект является гордым потомком"),
        (r"MayankOS превратилась в", "она превратилась в"),
        (r"Что делает MayankOS особенной\?", "Что делает её особенной?"),
        (r"MayankOS включает глубокую оптимизацию", "эта система включает глубокую оптимизацию"),
        (r"MayankOS берет этот невероятный", "Эта среда берет этот невероятный"),
        (r"MayankOS предлагает два основных способа", "Предлагается два основных способа"),
        (r"MayankOS специально разработана", "Эта система специально разработана"),
        (r"сделать MayankOS идеальной платформой", "сделать её идеальной платформой"),
        (r"MayankOS теперь использует Microsoft Edge", "система теперь использует Microsoft Edge"),
        (r"MayankOS позволяет легко переключиться", "конфигурация позволяет легко переключиться"),
        (r"MayankOS создана для того", "Эта среда создана для того"),
        (r"Идея MayankOS", "Идея этого проекта"),
        (r"используют MayankOS", "используют эту конфигурацию"),
        (r"MayankOS поддерживает несколько сред", "Поддерживается несколько сред"),
    ],
    "ja": [
        (r"MayankOS は、伝説的な ZaneyOS", "このプロジェクトは、伝説的な ZaneyOS"),
        (r"MayankOS は、伝説的な", "このプロジェクトは、伝説的な"),
        (r"MayankOS は独自のデザイン", "このディストリビューションは独自のデザイン"),
        (r"MayankOS の違いは何ですか\?", "何が違うのですか？"),
        (r"MayankOS は最新の AMD Ryzen", "このシステムは最新の AMD Ryzen"),
        (r"MayankOS はその素晴らしい基盤を受け継ぎ", "この環境はその素晴らしい基盤を受け継ぎ"),
        (r"MayankOS は、使い始めるための", "開始するための"),
        (r"MayankOS は、VLSI および", "このシステムは、VLSI および"),
        (r"MayankOS をハードウェア設計者のための究極の", "これをハードウェア設計者のための究極の"),
        (r"MayankOS は Microsoft Edge を使用するようになりました", "システムは Microsoft Edge を使用するようになりました"),
        (r"MayankOS では簡単に切り替えることができます", "この構成では簡単に切り替えることができます"),
        (r"MayankOS はあなたの個人的なワークステーション", "この環境はあなたの個人的なワークステーション"),
        (r"MayankOS の全体的なアイデアは", "このプロジェクトの全体的なアイデアは"),
        (r"MayankOS を動かしています", "この構成を動かしています"),
        (r"MayankOS は複数の環境をサポートしています", "複数の環境がサポートされています"),
    ],
    "hi": [
        (r"MayankOS पौराणिक ZaneyOS", "यह प्रोजेक्ट पौराणिक ZaneyOS"),
        (r"MayankOS अपने स्वयं के फोकस", "यह अपने स्वयं के फोकस"),
        (r"MayankOS को क्या अलग बनाता है\?", "इसे क्या अलग बनाता है?"),
        (r"MayankOS में नवीनतम AMD Ryzen", "इस सिस्टम में नवीनतम AMD Ryzen"),
        (r"MayankOS उस अविश्वसनीय आधार", "यह एनवायरनमेंट उस अविश्वसनीय आधार"),
        (r"MayankOS शुरू करने के दो प्राथमिक तरीके", "यहाँ शुरू करने के दो प्राथमिक तरीके"),
        (r"MayankOS को विशेष रूप से", "यह सिस्टम विशेष रूप से"),
        (r"MayankOS को हार्डवेयर डिजाइनरों के लिए", "इसे हार्डवेयर डिजाइनरों के लिए"),
        (r"MayankOS Microsoft Edge का उपयोग", "सिस्टम Microsoft Edge का उपयोग"),
        (r"MayankOS स्विच करना आसान", "कॉन्फ़िगरेशन स्विच करना आसान"),
        (r"MayankOS को आपकी व्यक्तिगत वर्कस्टेशन", "यह एनवायरनमेंट आपकी व्यक्तिगत वर्कस्टेशन"),
        (r"MayankOS का पूरा विचार", "इस प्रोजेक्ट का पूरा विचार"),
        (r"MayankOS चला रहे हैं", "इस कॉन्फ़िगरेशन का उपयोग कर रहे हैं"),
        (r"MayankOS कई वातावरणों का समर्थन", "यह कई वातावरणों का समर्थन"),
    ],
    "pt": [
        (r"MayankOS é um orgulhoso", "Este projeto é um orgulhoso"),
        (r"MayankOS evoluiu", "ele evoluiu"),
        (r"torna o MayankOS diferente", "o torna diferente"),
        (r"MayankOS inclui optimizações", "este sistema inclui optimizações"),
        (r"MayankOS pega nessa base", "Este ambiente pega nessa base"),
        (r"MayankOS oferece duas formas", "São oferecidas duas formas"),
        (r"MayankOS foi concebido", "Este sistema foi concebido"),
        (r"tornar o MayankOS a plataforma", "tornar esta a plataforma"),
        (r"MayankOS utiliza agora", "o sistema utiliza agora"),
        (r"MayankOS facilita a mudança", "a configuração facilita a mudança"),
        (r"MayankOS foi concebido para ser", "Este ambiente foi concebido para ser"),
        (r"ideia do MayankOS", "ideia deste projeto"),
        (r"utilizam o MayankOS", "utilizam esta configuração"),
        (r"MayankOS suporta vários", "São suportados vários"),
    ],
    "it": [
        (r"MayankOS è un orgoglioso", "Questo progetto è un orgoglioso"),
        (r"MayankOS si è evoluto", "si è evoluto in una distribuzione"),
        (r"rende MayankOS diverso", "lo rende diverso"),
        (r"MayankOS include ottimizzazioni", "questo sistema include ottimizzazioni"),
        (r"MayankOS prende questa base", "Questo ambiente prende questa base"),
        (r"MayankOS offre due modi", "Vengono offerti due modi"),
        (r"MayankOS è progettato", "Questo sistema è progettato"),
        (r"rendere MayankOS la piattaforma", "rendere questa la piattaforma"),
        (r"MayankOS utilizza ora", "il sistema utilizza ora"),
        (r"MayankOS rende facile", "la configurazione rende facile"),
        (r"L'idea di MayankOS", "L'idea di questo progetto"),
        (r"utilizzano MayankOS", "utilizzano questa configurazione"),
        (r"MayankOS supporta più", "Sono supportati più"),
    ],
    "bn": [
        (r"MayankOS কিংবদন্তি ZaneyOS", "এই প্রকল্পটি কিংবদন্তি ZaneyOS"),
        (r"MayankOS নিজস্ব ফোকাস", "এটি নিজস্ব ফোকাস"),
        (r"MayankOS কে কী আলাদা করে তোলে\?", "এটি কী আলাদা করে তোলে?"),
        (r"MayankOS-এ সর্বশেষ AMD Ryzen", "এই সিস্টেমে সর্বশেষ AMD Ryzen"),
        (r"MayankOS সেই অবিশ্বাস্য ভিত্তি", "এই এনভায়রনমেন্ট সেই অবিশ্বাস্য ভিত্তি"),
        (r"MayankOS শুরু করার দুটি প্রাথমিক উপায়", "শুরু করার দুটি প্রাথমিক উপায় অফার করা হয়েছে"),
        (r"MayankOS বিশেষভাবে VLSI", "এই সিস্টেমটি বিশেষভাবে VLSI"),
        (r"MayankOS কে হার্ডওয়্যার ডিজাইনারদের", "এটিকে হার্ডওয়্যার ডিজাইনারদের"),
        (r"MayankOS এখন Microsoft Edge", "সিস্টেমটি এখন Microsoft Edge"),
        (r"MayankOS পরিবর্তন করা সহজ", "কনফিগারেশনটি পরিবর্তন করা সহজ"),
        (r"MayankOS আপনার ব্যক্তিগত ওয়ার্কস্টেশন", "এই এনভায়রনমেন্ট আপনার ব্যক্তিগত ওয়ার্কস্টেশন"),
        (r"MayankOS এর পুরো ধারণাটি", "এই প্রকল্পের পুরো ধারণাটি"),
        (r"MayankOS চালাচ্ছেন", "এই কনফিগারেশনটি চালাচ্ছেন"),
        (r"MayankOS একাধিক পরিবেশ", "এটি একাধিক পরিবেশ"),
    ],
    "kn": [
        (r"MayankOS ಪೌರಾಣಿಕ ZaneyOS", "ಈ ಪ್ರಾಜೆಕ್ಟ್ ಪೌರಾಣಿಕ ZaneyOS"),
        (r"MayankOS ತನ್ನದೇ ಆದ ಗಮನವನ್ನು", "ಇದು ತನ್ನದೇ ಆದ ಗಮನವನ್ನು"),
        (r"MayankOS ಅನ್ನು ಯಾವುದು ವಿಭಿನ್ನವಾಗಿಸುತ್ತದೆ\?", "ಇದು ಯಾವುದು ವಿಭಿನ್ನವಾಗಿಸುತ್ತದೆ?"),
        (r"MayankOS ಇತ್ತೀಚಿನ AMD Ryzen", "ಈ ಸಿಸ್ಟಮ್ ಇತ್ತೀಚಿನ AMD Ryzen"),
        (r"MayankOS ಆ ನಂಬಲಾಗದ ಅಡಿಪಾಯವನ್ನು", "ಈ ಪರಿಸರವು ಆ ನಂಬಲಾಗದ ಅಡಿಪಾಯವನ್ನು"),
        (r"MayankOS ಪ್ರಾರಂಭಿಸಲು ಎರಡು ಪ್ರಾಥಮಿಕ ಮಾರ್ಗಗಳನ್ನು", "ಪ್ರಾರಂಭಿಸಲು ಎರಡು ಪ್ರಾಥಮಿಕ ಮಾರ್ಗಗಳನ್ನು ನೀಡಲಾಗಿದೆ"),
        (r"MayankOS ಅನ್ನು ವಿಶೇಷವಾಗಿ VLSI", "ಈ ಸಿಸ್ಟಮ್ ಅನ್ನು ವಿಶೇಷವಾಗಿ VLSI"),
        (r"MayankOS ಅನ್ನು ಹಾರ್ಡ್‌ವೇರ್ ಡಿಸೈನರ್‌ಗಳಿಗೆ", "ಇದನ್ನು ಹಾರ್ಡ್‌ವೇರ್ ಡಿಸೈನರ್‌ಗಳಿಗೆ"),
        (r"MayankOS ಈಗ Microsoft Edge", "ಸಿಸ್ಟಮ್ ಈಗ Microsoft Edge"),
        (r"MayankOS ಬದಲಾಯಿಸುವುದನ್ನು ಸುಲಭಗೊಳಿಸುತ್ತದೆ", "ಕಾನ್ಫಿಗರೇಶನ್ ಬದಲಾಯಿಸುವುದನ್ನು ಸುಲಭಗೊಳಿಸುತ್ತದೆ"),
        (r"MayankOS ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ವರ್ಕ್‌ಸ್ಟೇಷನ್ ಆಗಲು", "ಈ ಪರಿಸರವು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ವರ್ಕ್‌ಸ್ಟೇಷನ್ ಆಗಲು"),
        (r"MayankOS ನ ಸಂಪೂರ್ಣ ಕಲ್ಪನೆಯು", "ಈ ಪ್ರಾಜೆಕ್ಟ್ ನ ಸಂಪೂರ್ಣ ಕಲ್ಪನೆಯು"),
        (r"MayankOS ಅನ್ನು ಚಲಾಯಿಸುತ್ತಿದ್ದಾರೆ", "ಈ ಕಾನ್ಫಿಗರೇಶನ್ ಅನ್ನು ಚಲಾಯಿಸುತ್ತಿದ್ದಾರೆ"),
        (r"MayankOS ಬಹು ಪರಿಸರಗಳನ್ನು", "ಇದು ಬಹು ಪರಿಸರಗಳನ್ನು"),
    ],
    "ta": [
        (r"MayankOS புகழ்பெற்ற ZaneyOS", "இந்த திட்டம் புகழ்பெற்ற ZaneyOS"),
        (r"MayankOS அதன் சொந்த கவனத்துடன்", "இது அதன் சொந்த கவனத்துடன்"),
        (r"MayankOS ஐ எது வேறுபடுத்துகிறது\?", "இதனை எது வேறுபடுத்துகிறது?"),
        (r"MayankOS சமீபத்திய AMD Ryzen", "இந்த அமைப்பு சமீபத்திய AMD Ryzen"),
        (r"MayankOS அந்த நம்பமுடியாத அடித்தளத்தை", "இந்த சூழல் அந்த நம்பமுடியாத அடித்தளத்தை"),
        (r"MayankOS தொடங்குவதற்கு இரண்டு முதன்மை வழிகளை", "தொடங்குவதற்கு இரண்டு முதன்மை வழிகள் வழங்கப்படுகின்றன"),
        (r"MayankOS குறிப்பாக VLSI", "இந்த அமைப்பு குறிப்பாக VLSI"),
        (r"MayankOS ஐ வன்பொருள் வடிவமைப்பாளர்களுக்கான", "இதனை வன்பொருள் வடிவமைப்பாளர்களுக்கான"),
        (r"MayankOS இப்போது Microsoft Edge", "இந்த அமைப்பு இப்போது Microsoft Edge"),
        (r"MayankOS மாற்றுவதை எளிதாக்குகிறது", "இந்த கட்டமைப்பு மாற்றுவதை எளிதாக்குகிறது"),
        (r"MayankOS உங்கள் தனிப்பட்ட பணிநிலையமாக", "இந்த சூழல் உங்கள் தனிப்பட்ட பணிநிலையமாக"),
        (r"MayankOS இன் முழு யோசனையும்", "இந்த திட்டத்தின் முழு யோசனையும்"),
        (r"MayankOS ஐ இயக்குகிறார்கள்", "இந்த கட்டமைப்பை இயக்குகிறார்கள்"),
        (r"MayankOS பல சூழல்களை", "இது பல சூழல்களை"),
    ],
    "te": [
        (r"MayankOS పురాణ ZaneyOS", "ఈ ప్రాజెక్ట్ పురాణ ZaneyOS"),
        (r"MayankOS తనదైన దృష్టితో", "ఇది తనదైన దృష్టితో"),
        (r"MayankOS ని ఏది భిన్నంగా చేస్తుంది\?", "దీనిని ఏది భిన్నంగా చేస్తుంది?"),
        (r"MayankOS లో సరికొತ್ತ AMD Ryzen", "ఈ సిస్టమ్ లో సరికొత్త AMD Ryzen"),
        (r"MayankOS ఆ అద్భుతమైన పునాదిని", "ఈ పర్యావరణం ఆ అద్భుతమైన పునాదిని"),
        (r"MayankOS ప్రారంభించడానికి రెండు ప్రాథమిక మార్గాలను", "ప్రారంభించడానికి రెండు ప్రాథమిక మార్గాలు అందించబడ్డాయి"),
        (r"MayankOS ప్రత్యేకంగా VLSI", "ఈ సిస్టమ్ ప్రత్యేకంగా VLSI"),
        (r"MayankOS ని హార్డ్‌వేర్ డిజైనర్ల కోసం", "దీనిని హార్డ్‌వేర్ డిజైనర్ల కోసం"),
        (r"MayankOS ఇప్పుడు Microsoft Edge", "సిస్టమ్ ఇప్పుడు Microsoft Edge"),
        (r"MayankOS మార్చడాన్ని సులభతరం చేస్తుంది", "కాన్ఫిగరేషన్ మార్చడాన్ని సులభతరం చేస్తుంది"),
        (r"MayankOS మీ వ్యక్తిగత వర్క్‌స్టేషన్‌గా", "ఈ పర్యావరణం మీ వ్యక్తిగత వర్క్‌స్టేషన్‌గా"),
        (r"MayankOS యొక్క మొత్తం ఆలోచన", "ఈ ప్రాజెక్ట్ యొక్క మొత్తం ఆలోచన"),
        (r"MayankOSని నడుపుతున్నారు", "ఈ కాన్ఫిగరేషన్‌ను నడుపుతున్నారు"),
        (r"MayankOS బహుళ పర్యావరణాలకు", "ఇది బహుళ పర్యావరణాలకు"),
    ],
    "sa": [
        (r"MayankOS पौराणिक ZaneyOS", "एषा परियोजना पौराणिक ZaneyOS"),
        (r"MayankOS स्वकीयेन लक्ष्येण सह", "एतत् स्वकीयेन लक्ष्येण सह"),
        (r"MayankOS किं भिन्नं करोति\?", "एतत् किं भिन्नं करोति?"),
        (r"MayankOS मध्ये नवीनतमं AMD Ryzen", "एतस्यां प्रणाल्यां नवीनतमं AMD Ryzen"),
        (r"MayankOS तं अविश्वसनीयं आधारं", "एतत् वातावरणम् तं अविश्वसनीयं आधारं"),
        (r"MayankOS आरम्भार्थं द्वौ प्राथमिकौ मार्गौ", "आरम्भार्थं द्वौ प्राथमिकौ मार्गौ प्रदत्तौ"),
        (r"MayankOS विशेषतः VLSI", "एषा प्रणाली विशेषतः VLSI"),
        (r"MayankOS हार्डवेयर-डिजाइनर-कृते अन्तिमं", "एतत् हार्डवेयर-डिजाइनर-कृते अन्तिमं"),
        (r"MayankOS अधुना Microsoft Edge", "एषा प्रणाली Microsoft Edge"),
        (r"MayankOS परिवर्तनं सुलभं करोति", "एषा रचना परिवर्तनं सुलभं करोति"),
        (r"MayankOS भवतः व्यक्तिगतकार्यस्थानं", "एतत् वातावरणम् भवतः व्यक्तिगतकार्यस्थानं"),
        (r"MayankOS इत्यस्य पूर्णः विचारः", "अस्याः परियोजनायाः पूर्णः विचारः"),
        (r"MayankOS चालयन्ति", "एतां रचनां चालयन्ति"),
        (r"MayankOS अनेकवातावरणानि समर्थयति", "एतत् अनेकवातावरणानि समर्थयति"),
    ]
}

# Add Arabic, Bhojpuri, and Traditional Chinese if needed, although counts were low
# Let's skip them for now as per instructions they were already low.

for lang, pair_list in replacements.items():
    file_path = f"README.{lang}.md"
    if not os.path.exists(file_path):
        continue
    
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    for pattern, repl in pair_list:
        content = re.sub(pattern, repl, content)
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
